# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ludovic Bouguerra
email: bouguerra.ludovic@gmail.com
phone: +33 6 81 93 15 60
description: Développeur freelance Marseille, Aix, Montreal #Web #Video #Embarqué #Architecture #Docker #Odoo Spécialiste en architecture des applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ludovicbouguerra.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LBouguerra
github_username:  ludovic-bouguerra
linkedin: http://fr.linkedin.com/pub/ludovic-bouguerra/34/5a/214/
gplus_username: LudovicBouguerra
skype_username: ludovic.bouguerra
main_categories:
  - Architecture logicielle
  - Développement
  - Diffusion sur internet
  - FFmpeg
  - OpenERP
  - référencement
  - Systèmes d'informations
  - Vidéo
  - Virtualisation
plugins:
  - jekyll-paginate
paginate: 5
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
sass:
    style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
plugins:
  - jekyll-redirect-from
