# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ludovic Bouguerra
email: bouguerra.ludovic@gmail.com
phone: +33 6 81 93 15 60
description: Développeur freelance Web / Video / Embarqué / Odoo - Marseille / Aix / Montréal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ludovicbouguerra.fr" # the base hostname & protocol for your site, e.g. http://example.com
technologies:
  aosp:
    picture: image/home/technologies/aosp.png
    name: Android AOSP
  yocto:
    picture: image/home/technologies/yocto.png
    name: Yocto
  buildroot:
    picture: image/home/technologies/buildroot.png
    name: Buildroot
  linux:
    picture: image/home/technologies/linux.png
    name: Linux, drivers
  gstreamer:
    picture: image/home/technologies/gstreamer.png
    name: Gstreamer
  symfony:
    picture: image/home/technologies/symfony.png
    name: Symfony
  google:
    picture: image/home/technologies/google.png
    name: Google Analytics
  cas:
    picture: image/home/technologies/cas.png
    name: CAS
  jquery:
    picture: image/home/technologies/jquery.png
    name: JQuery
  git:
    picture: image/home/technologies/git.png
    name: Git
  proxmox:
    picture: image/home/technologies/proxmox.png
    name: Proxmox
  odoo:
    picture: image/home/technologies/openerp.png
    name: Odoo
  java:
    picture: image/home/technologies/java.png
    name: Java
  debian:
    picture: image/home/technologies/debian.png
    name: Debian
  wowza:
    picture: image/home/technologies/wowza.png
    name: Wowza media server
  play:
    picture: image/home/technologies/playframework.png
    name: Play framework
twitter_username: LBouguerra
github_username:  ludovic-bouguerra
linkedin: http://fr.linkedin.com/pub/ludovic-bouguerra/34/5a/214/
gplus_username: LudovicBouguerra
skype_username: ludovic.bouguerra
main_categories:
  - Architecture logicielle
  - Développement
  - Diffusion sur internet
  - FFmpeg
  - OpenERP
  - référencement
  - Systèmes d'informations
  - Vidéo
  - Virtualisation
plugins:
  - jekyll-paginate
paginate: 5
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
sass:
    style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
plugins:
  - jekyll-redirect-from
